# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170606_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mapobjective',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mapobjective',
            name='value',
        ),
        migrations.AddField(
            model_name='game',
            name='length',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='mapobjective',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Event'),
        ),
    ]
