# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170606_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='value',
        ),
        migrations.RemoveField(
            model_name='mapobjective',
            name='event',
        ),
        migrations.RemoveField(
            model_name='mapobjective',
            name='stat',
        ),
        migrations.AddField(
            model_name='event',
            name='mapObjective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.MapObjective'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Stat'),
        ),
        migrations.AddField(
            model_name='mapobjective',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mapobjective',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
